### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#11]
When I run "python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure", the following error occurred.

```
# python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|█████████████████████████████████████████████████| 97.8M/97.8M [00:08<00:00, 11.7MB/s]
  0%|                                                               | 0/68 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ishihara/Panic3d/panic3d-anime-reconstruction/_scripts/eval/generate.py", line 82, in <module>
    x = dk[bn]
  File "/home/ishihara/Panic3d/panic3d-anime-reconstruction/_databacks/lustrous_renders_v1.py", line 183, in __getitem__
    ret['image'] = I(f'{self.dn}/renders/{bn}.png')
  File "/home/ishihara/Panic3d/panic3d-anime-reconstruction/_util/twodee_v1.py", line 114, in __init__
    self.__init__(Image.open(self.data))
  File "/opt/conda/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './_data/lustrous/renders/daredemoE/fandom_align/genshin/aether/front.png'
```

Please let me know how to fix it.

**Comment by ShuhongChen** [comment]
please follow instructions
https://github.com/ShuhongChen/panic3d-anime-reconstruction#download

**Comment by Ishihara-Masabumi** [comment]
The message is saying that No such file or directory: './_data/lustrous/renders/daredemoE/fandom_align/genshin/aether/front.png'.
But, I found that there is a 'aether/front.png' file in 'animerecon-benchmark/_data/lustrous/renders/daredemoE/fandom_align_seg/genshin/aether/front.png', so the directory 'andom_align' is different from 'fandom_align_seg'.
Then, if the solution of this issue is the change the directory name from 'fandom_align_seg' to 'andom_align', I ca understaind.

**Comment by ShuhongChen** [comment]
You need to download the actual image data for Aether from the animerecon-benchmark repo, and follow the instructions there; the "seg" data you see is just segmentation masks, and doesn't have color information

The animerecon-benchmark repo will download Aether image, crop/realign it, then composite with the segmentation

**Comment by Ishihara-Masabumi** [comment]
I can't find fandom_align directory by downloading animerecon-benchmark repo.
Please tell me the specific steps to get fandom_align data.

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/animerecon-benchmark#download
^ please follow each step in downloads section; fandom_align are "genshin2d" and "hololive2d" sections

**Comment by louis-fashion-ai** [comment]
First, "aether/front.png" can't be downloaded correctly, so I delete it in daredemoE_test.csv. Second, I also get error: FileNotFoundError: [Errno 2] No such file or directory: './_data/lustrous/renders/daredemoE/ortho/genshin/albedo/front.png', but I can't find the download method for the ortho file

**Comment by ShuhongChen** [comment]
Please make sure to download the data from the other data download repos:
https://github.com/ShuhongChen/panic3d-anime-reconstruction#download

Your specific aether png should be downloaded+rendered from:
https://github.com/ShuhongChen/animerecon-benchmark (download)
https://github.com/ShuhongChen/vroid_renderer (render)
