### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by naruya** [ShuhongChen/panic3d-anime-reconstruction#15]
Thank you for your excellent work!
I would like to make a research based on yours, could you please publish the training script?

(`. /_train/eg3dc/runs/ecrutileE_eclustrousC_n120/ecrutileE_eclustrousC_n120.sh` was not found...)

**Comment by naruya** [comment]
I'm really sorry, I found it. Thank you.

**Comment by ShuhongChen** [comment]
No problem, glad you found it
