### ISSUE TITLE
https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/supplementary/art_attributions.txt#L93

### ISSUE THREAD

**Issue by Master12345qe** [ShuhongChen/panic3d-anime-reconstruction#17]
https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/supplementary/art_attributions.txt#L93

**Comment by ShuhongChen** [comment]
I'm assuming this issue was opened by mistake?
