### ISSUE TITLE
[question] how was  "fandom_align_alignment.pkl" made ? 

### ISSUE THREAD

**Issue by tky5622** [ShuhongChen/panic3d-anime-reconstruction#18]
Hi, thank you for the great work!
I would like to apply this method to another image but "fandom_align_alignment.pkl" seems to be prepared for specific images.
So, it would be nice if I could catch up the details of this pkl file.
thank you in advance !

**Comment by ShuhongChen** [comment]
Hi, thanks for using our project

> "fandom_align_alignment.pkl" seems to be prepared for specific images.

Yes, that's right; sorry, after looking around I realized we never explicitly wrote down the alignment method.  The alignment is based on [hysts anime face detector](https://github.com/hysts/anime-face-detector) which is very good.  We calculated statistics of keypoints extracted across all front-facing orthographic renders, and align new images to match those stats.

This method should get you the transform matrix for new images given keypoints.  Note that keypoint coordinates and output matrix are matrix-image-convention (xy-flip of hysts output), and that this assumes the source face is oriented correctly (doesn't need rotation, no head tilt).  For the project we added some random noise only to x-center (head height level), but for inference you can remove if you want

```python
# mean+std of hysts-keypoints statistics of rendered front-images
# image size is 512x512
x_mu, x_sig = (294.9637, 8.072594)   # center x-coord (+down)
y_mu, y_sig = (255.8569, 1.8546647)  # center y-coord (+right)
a_mu, a_sig = (13.3556, 2.529512)  # std of keypoints from center
def face_alignment_transform(keypoints):
    # calc stats
    kpts = keypoints
    c = kpts.mean(axis=0)
    s = np.linalg.norm(kpts-c, axis=1).std()
    rands = np.random.normal(size=3)
    cnew = np.asarray([
        x_mu + x_sig*rands[0],
        y_mu, #+ y_sig*rands[1],
    ])
    snew = a_mu #+ a_sig*rands[2]

    # get matrix
    sf = snew / s
    M = np.asarray([  # recenter to new
        [1,0,cnew[0]],
        [0,1,cnew[1]],
        [0,0,1],
    ]) @ np.asarray([  # scale
        [sf,0,0],
        [0,sf,0],
        [0,0,1],
    ]) @ np.asarray([  # center to origin
        [1,0,-c[0]],
        [0,1,-c[1]],
        [0,0,1],
    ])
    return M
```

edit: corrected the `a_mu, a_sig` values which were wrong before
