### ISSUE TITLE
I don't understand this

### ISSUE THREAD

**Issue by Feewox** [ShuhongChen/panic3d-anime-reconstruction#19]
I don't undesrtand how to set up any repo because i don't know thing of programming stuff, can you explain better for someone who is dumb in this websside like me? please

**Comment by ShuhongChen** [comment]
Hi, thanks for your interest in our project.  The project setup is geared towards researchers; you'd need at least to spend some time with the tools to use it.  If you have specific questions we maybe can give pointers
