### ISSUE TITLE
Inference data

### ISSUE THREAD

**Issue by zeng-yifei** [ShuhongChen/panic3d-anime-reconstruction#2]
Hi, this work really produces impressive result in the demo. I also try to build the repo and I have downloaded all the data from goole drive. But I found it too big to download all the necessary data listed in the repo. I wonder if I JUST want to run the inferece, then what data I should obtain?

P.S. now I run the _script.generate.py and it produces error like this: 
`No such file or directory: './_data/danbooru/_filters/intently_combatively_rules.json`
Which dataset should I download to get this data? 
Hope for your answer : )

**Comment by ShuhongChen** [comment]
> I wonder if I JUST want to run the inferece, then what data I should obtain?

For evaluation, supposedly all you need is:
1) merging all downloads from the drive folder
2) [animerecon-benchmark](https://github.com/ShuhongChen/animerecon-benchmark)
3) [vroid_renderer](https://github.com/ShuhongChen/vroid_renderer#animerecon-benchmark), just the animerecon-benchmark part

I know some of these downloads/rendering scripts maybe a bit complicated to run; sorry we can't release a direct download of the data

> No such file or directory: './_data/danbooru/_filters/intently_combatively_rules.json

Sorry about that, it's from our prev project [bizarre-pose-estimator](https://github.com/ShuhongChen/bizarre-pose-estimator) and I forgot to include the metadata in the panic3d zip

I reuploaded `panic3d-anime-reconstruction.zip` to the panic3d [drive](https://drive.google.com/drive/folders/1Zpt9x_OlGALi-o-TdvBPzUPcvTc7zpuV?usp=sharing) to include missing files; please let me know if you have any other issues

**Comment by zeng-yifei** [comment]
Thank you for your kind and detailed reply~

I will try to download the updated files later : -)

**Comment by maocaixia** [comment]
Have you solved the problem ? @zeng-yifei
