### ISSUE TITLE
Can I test my own images by modifying _scripts.eval.generate?

### ISSUE THREAD

**Issue by MasonSunGo** [ShuhongChen/panic3d-anime-reconstruction#21]
or, is there some guide to test my own images? thanks!

**Comment by ShuhongChen** [comment]
Hello, sorry but we don't have a script for your own images yet; we might add one based on the planned cvpr demo if we have time

For now if you'd still like to try, supposedly the only missing component is face alignment, discussed in [this issue](https://github.com/ShuhongChen/panic3d-anime-reconstruction/issues/18#issuecomment-1546734206); the rest of the preprocessing and datatypes are handled by the generate script if I'm not wrong

If you encounter any missing/inexplicable datatypes I can take a look and offer some tips
