### ISSUE TITLE
Is the pre-trained discriminator available?

### ISSUE THREAD

**Issue by naruya** [ShuhongChen/panic3d-anime-reconstruction#23]
I am planning to use your code with my original dataset.
In the training script, there is a line
`--resume_discrim=./_data/eg3d/networks/ffhq512-128.pkl`, and within the [train_loop](https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_train/eg3dc/src/training/training_loop_v0.py#L178-L184C42), it mentions
```
    # Resume from existing pickle's discriminator. (shu added)
    if (resume_discrim_pkl is not None) and (rank == 0):
        print(f'Resuming discriminator from "{resume_discrim_pkl}"')
        with dnnlib.util.open_url(resume_discrim_pkl) as f:
            resume_data_discrim = legacy.load_network_pkl(f)
        for name, module in [('D', D), ]:
            misc.copy_params_and_buffers(resume_data_discrim[name], module, require_all=False)
```

suggesting it loads a pre-trained discriminator model.
Is this pickle file available to the public...? (or...... it would be greatly appreciated if you could make it available.)

thanks.

**Comment by ShuhongChen** [comment]
Yes, these are actually the pretrained eg3d ffhq models; you should be able to find them here:
https://github.com/NVlabs/eg3d/blob/main/docs/models.md#ffhq

**Comment by naruya** [comment]
thank you very much!
