### ISSUE TITLE
all steps completed but im getting this error

### ISSUE THREAD

**Issue by CamiloB4A** [ShuhongChen/panic3d-anime-reconstruction#24]
python3 -m _scripts.eval.generate
Traceback (most recent call last):
  File "/home/camib4a/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/camib4a/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/f/repos/panic3d-anime-reconstruction-master/_scripts/eval/generate.py", line 7, in <module>
    from _util.twodee_v1 import * ; import _util.twodee_v1 as u2d
  File "/mnt/f/repos/panic3d-anime-reconstruction-master/_util/twodee_v1.py", line 28, in <module>
    _FN_ARIAL = f'{os.environ["PROJECT_DN"]}/_env/arial_monospaced_mt.ttf'
  File "/home/camib4a/anaconda3/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJECT_DN'

**Comment by tky5622** [comment]
you seem not to set PROJECT_DN.
Did you create "machine_config.bashrc" and set path ?

**Comment by CamiloB4A** [comment]
yes, all repos look like this: 
even i tried modify the script of generate.py changing manually the PROJECT_DN

 #!/bin/bash


export MACHINE_NAME=
export PROJECT_DN=/mnt/f/repos/panic3d-anime-reconstruction-master

export JUPYTERLAB_PORT=8889
export JUPYTERLAB_HOST=localhost

export MOUNTS_DOCKER="
"
export MOUNTS_SINGULARITY="
"

export SINGULARITY_CACHEDIR=
export SINGULARITY_TMPDIR=

**Comment by ShuhongChen** [comment]
Are you inside the docker container? i.e. did you run `make/shell_docker`?  Supposedly the `make/shell_docker` command takes care of setting the variables:
https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_env/make_config.bashrc#LL26C31-L26C31

**Comment by CamiloB4A** [comment]
Let me know, if for the eval script, is necessary load the container of Docker? because i got a different error

**Comment by ShuhongChen** [comment]
Unless you correctly set up all the dependencies in the dockerfile on your local install, the docker container is necessary; you can't run scripts with missing dependencies
