### ISSUE TITLE
How to make resnet features?

### ISSUE THREAD

**Issue by naruya** [ShuhongChen/panic3d-anime-reconstruction#25]
(I'm really sorry to keep asking you ...)

I'm encountering errors with these lines of code. Could you please explain how you created the features using ResNet?

https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_train/eg3dc/datasets/ecrutileE.py#L363-L368

**Comment by ShuhongChen** [comment]
> (I'm really sorry to keep asking you ...)

No worries, sorry I've just been busy this week

> explain how you created the features using ResNet?

I believe only `resnet_chonk` is needed if I'm not wrong; `resnet_feats` maybe leftover from older experiments and not actually accessed from the provided training script, you might be able to comment L363-365 out without affecting training

To get `resnet_chonk`, it is actually computed at inference time in the `generate.py` script [here](https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_scripts/eval/generate.py#LL92C5-L92C5); you should be able to preprocess these and save to the specific `front.pkl` location for reading during training

Sorry for the lack of training setup details, let me know if you have any more issues
