### ISSUE TITLE
Nice job, what should we do to reproduce your talking head demo? Would you mind providing the inference code?

### ISSUE THREAD

**Issue by THU-lsy** [ShuhongChen/panic3d-anime-reconstruction#3]
A inference code for any anime portrait image

**Comment by ShuhongChen** [comment]
Thanks, I'm glad you liked the project

The talking head demo is actually not fully-automatic; there's a bone placement and very hacky blendskinning weights step that we did manually in blender for the supplementary

It's possible to replace this with something like [rignet](https://arxiv.org/abs/2005.00559), but sorry we don't have time to try it and release it at the moment
