### ISSUE TITLE
How should I reproduce the generation effects shown in the project?

### ISSUE THREAD

**Issue by Pamimi** [ShuhongChen/panic3d-anime-reconstruction#30]
<img width="418" alt="image" src="https://github.com/ShuhongChen/panic3d-anime-reconstruction/assets/89392940/6946f201-04fb-49b2-a66e-ee35cc1488cc">
<img width="483" alt="image" src="https://github.com/ShuhongChen/panic3d-anime-reconstruction/assets/89392940/c36cdbf8-46b5-4b79-8a7d-5e315a7ca0dd">
<img width="444" alt="image" src="https://github.com/ShuhongChen/panic3d-anime-reconstruction/assets/89392940/12fc8ffe-ca51-4869-866f-bda655619b20">
<img width="382" alt="image" src="https://github.com/ShuhongChen/panic3d-anime-reconstruction/assets/89392940/75e5bf62-4a8a-4b86-b785-ba101e88271b">
As the title suggests, my reproduction results are significantly different from those shown on the main page. What could be the reason for this and can it be adjusted?

**Comment by ShuhongChen** [comment]
Hello, may I ask in what way you mean the results are different?  At a glance, your images seem roughly correct

**Comment by Pamimi** [comment]
Thank you for your reply! What I meant was, it seems that my generated results are somewhat blurry in some areas, unlike the fine details on the main page. Is there something I need to adjust?

**Comment by ShuhongChen** [comment]
> my generated results are somewhat blurry in some areas, unlike the fine details on the main page

Oh I see, I think the amount of blurriness is roughly correct; maybe the ones on the front page only seem sharper because the image size is smaller

Overall the quality at 512 is admittedly not that great (blurry, artifacts, bad shapes, etc.), we'll be trying to improve in future work

**Comment by Pamimi** [comment]
> 
> Oh I see, I think the amount of blurriness is roughly correct; maybe the ones on the front page only seem sharper because the image size is smaller
> 
> Overall the quality at 512 is admittedly not that great (blurry, artifacts, bad shapes, etc.), we'll be trying to improve in future work

Thank you, I understand now. Thank you for your reply. Looking forward to your excellent work in the future!

**Comment by maocaixia** [comment]
Hi, May I ask how you reproduce the generation? Very Thanks! @Pamimi
