### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './_data/lustrous/renders/rutileE/dorthoA/9/1265592699132249759/left.png'

### ISSUE THREAD

**Issue by louis-fashion-ai** [ShuhongChen/panic3d-anime-reconstruction#31]
I don‘t know how to get the dorthoA, there is no script to generate it.

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/panic3d-anime-reconstruction#download

Please follow instructions to download/render data
