### ISSUE TITLE
Where is the rmlineERA_train.pkl and rmlineERA_test.pkl?

### ISSUE THREAD

**Issue by onpix** [ShuhongChen/panic3d-anime-reconstruction#33]
Thank you for your exceptional contribution! I would like to evaluate the illustration-to-Render module separately, but I am unable to locate the necessary training and testing data, specifically `rmlineERA_train.pkl` and `rmlineERA_test.pkl`. Although I have downloaded `panic_data_models_merged.zip`, `panic_data_models_merged_data\lustrous\preprocessed\patch` appears to be empty. Looking forward to your response.

**Comment by ShuhongChen** [comment]
> I would like to evaluate the illustration-to-Render module separately

If you're just looking to evaluate (like the figure/table in the paper), the generation script actually processes line removal separately from the reconstruction; you can just iterate through the eval set using that part only.  IIRC, the pickle files are just preprocessed patches which only help track performance across training (not helpful for final eval)

Admittedly I'd need to do more digging to get the pickles to you...  If you super need them for something else I can try to look for them

**Comment by onpix** [comment]
I have evaluated the entire process as you suggested and it works. Thank you for your help!  I have one more question out of curiosity: If I want to train the line-removal model separately, would it be sufficient to use the data of `panic_data_models_merged.zip`?

**Comment by ShuhongChen** [comment]
> evaluated the entire process as you suggested and it works. Thank you for your help
Ok great, no problem!

> would it be sufficient to use the data of panic_data_models_merged.zip?
I think you'd need to download/render the data from the other repos too (vtubers+vroids for unpaired training, animerecon for eval); we're not allowed to host the copyrighted data directly in the zip...
