### ISSUE TITLE
reproduce my own image

### ISSUE THREAD

**Issue by maocaixia** [ShuhongChen/panic3d-anime-reconstruction#37]
Thanks for your work. 

How to generate 3D reconstruction with my own single image ?  Is there a script for that? thanks ! 

@ShuhongChen

**Comment by maocaixia** [comment]
Or is there any instructions for models to process?

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/panic3d-anime-reconstruction/issues/21#issuecomment-1563795940
