### ISSUE TITLE
How to convert the 'front.pkl' to 3D model file like .vrm

### ISSUE THREAD

**Issue by liangliangdeveloper** [ShuhongChen/panic3d-anime-reconstruction#38]
Thanks for your work!

I wonder how to generate 'front.pkl' can be converted into a 3d model file that I can visualize in Blender.

=================

感谢你的工作！

我想知道如何可以把生成的front.pkl文件变成常用的3d文件，例如vrm，我希望在Blender中可视化这些模型

**Comment by ShuhongChen** [comment]
Hello, unfortunately we don't have a script that does this, but the generated `front.pkl` has the verts, faces, and vertex-colors you need to write an obj

There are some libraries that help you write obj files, for example here:
https://libigl.github.io/libigl-python-bindings/igl_docs/#write_obj
