### ISSUE TITLE
Can you make this project run on windows ealiy?

### ISSUE THREAD

**Issue by h2440222798** [ShuhongChen/panic3d-anime-reconstruction#6]
I am using the pycharm and python 3.6 on my own computer, but I can't download genshen and only use virtualyoutuber dataset.
So the file structure is not right, and can you upload the dataset on baidu pandesk? thank you

**Comment by tzx666** [comment]
i try it on windows by using docker, but the terminal had no output, can the author give a setup on wsl?

**Comment by h2440222798** [comment]
> i try it on windows by using docker, but the terminal had no output, can the author give a setup on wsl?

I want to use wsl but ....... I can not download dataset..... so i can not start the first step....

**Comment by ShuhongChen** [comment]
> can you upload the dataset on baidu pandesk?

Sorry for the trouble, we're not allowed to host the data...

> i try it on windows by using docker, but the terminal had no output

I'm not sure what you mean by this; if you have a docker container running properly you should be able to use the commands?

> can the author give a setup on wsl?

I'm not familiar with WSL, but from what I understand you install docker in WSL, and it shoudl work in there

> I want to use wsl but ....... I can not download dataset

I'm not sure which dataset you're having trouble with?  The scripts run with genshin/hololive data in the benchmark: https://github.com/ShuhongChen/animerecon-benchmark
