### ISSUE TITLE
shell_docker error 2

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#7]
After make/docker_pull, I tried to run make/shell_docker.
But, the following error occurred.

```
$ make/shell_docker
non-network local connections being added to access control list
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Please let me know how to fix it.

**Comment by ShuhongChen** [comment]
The project requires a linux machine with gpu; it seems you either don't have a gpu, or it's not configured properly with docker?
