### ISSUE TITLE
shell_docker error 3

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#9]
After make/docker_pull, I tried to run make/shell_docker.
But, the following error occurred.

```
$ make/shell_docker
non-network local connections being added to access control list
```

Please let me know how to fix it.

**Comment by ShuhongChen** [comment]
I don't think this is an error, it shouldn't cause issues for you

**Comment by nashpan** [comment]
@Ishihara-Masabumi  have you solved the problem, I meet the same problem, I am a newer about docker, could you please help me solve the problem? Thanks

**Comment by Ishihara-Masabumi** [comment]
I have solved this problem.
I found that after make/shell_docker, you are in the docker and changed to root.
Maybe this environment is good for execution.
